Resources:

  # ---------------------------------------------------------
  # SNS role used by Cognito SMS configuration (for MFA)
  # Name: sns-<env>-<8char-guid-from-StackId>
  # ---------------------------------------------------------
  SNSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - 'sns'
          - !Ref env
          - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref 'AWS::StackId'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ""
            Effect: "Allow"
            Principal:
              Service: "cognito-idp.amazonaws.com"
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: photosb143529b_role_external_id
      Policies:
        - PolicyName: photosb143529b-sns-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource: "*"

  # ---------------------------------------------------------
  # User Pool and Clients
  # ---------------------------------------------------------
  UserPool:
    Type: AWS::Cognito::UserPool
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !If [ShouldNotCreateEnvResources, !Ref userPoolName, !Join ['',[!Ref userPoolName, '-', !Ref env]]]
      Schema:
        - Name: email
          Required: true
          Mutable: true
      AutoVerifiedAttributes: !Ref autoVerifiedAttributes
      EmailVerificationMessage: !Ref emailVerificationMessage
      EmailVerificationSubject: !Ref emailVerificationSubject
      Policies:
        PasswordPolicy:
          MinimumLength: !Ref passwordPolicyMinLength
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      MfaConfiguration: !Ref mfaConfiguration
      SmsVerificationMessage: !Ref smsVerificationMessage
      SmsConfiguration:
        SnsCallerArn: !GetAtt SNSRole.Arn
        ExternalId: photosb143529b_role_external_id

  UserPoolClientWeb:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: photosb143529b_app_clientWeb
      RefreshTokenValidity: !Ref userpoolClientRefreshTokenValidity
      UserPoolId: !Ref UserPool
    DependsOn: UserPool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: photosb143529b_app_client
      GenerateSecret: !Ref userpoolClientGenerateSecret
      RefreshTokenValidity: !Ref userpoolClientRefreshTokenValidity
      UserPoolId: !Ref UserPool
    DependsOn: UserPool

  # ---------------------------------------------------------
  # Role for the custom resource Lambda
  # Name: upClientLambdaRole-<env>-<8char-guid-from-StackId>
  # ---------------------------------------------------------
  UserPoolClientRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - 'upClientLambdaRole'
          - !Ref env
          - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref 'AWS::StackId'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
    DependsOn: UserPoolClient

  # ---------------------------------------------------------
  # Python custom resource Lambda (no aws-sdk needed)
  # ---------------------------------------------------------
  UserPoolClientLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Timeout: 300
      Role: !GetAtt [UserPoolClientRole, Arn]
      Code:
        ZipFile: |
          import json
          import urllib.request
          import boto3

          identity = boto3.client('cognito-idp')

          def send_response(event, context, status, data=None, reason=None, physical_id=None):
            body = {
              "Status": status,
              "Reason": reason or f"See CloudWatch Log Stream: {getattr(context, 'log_stream_name', 'unknown')}",
              "PhysicalResourceId": physical_id or getattr(context, 'log_stream_name', 'custom-resource'),
              "StackId": event["StackId"],
              "RequestId": event["RequestId"],
              "LogicalResourceId": event["LogicalResourceId"],
              "Data": data or {}
            }
            blob = json.dumps(body).encode("utf-8")
            req = urllib.request.Request(
              url=event["ResponseURL"],
              data=blob,
              method="PUT",
              headers={"content-type": "", "content-length": str(len(blob))}
            )
            with urllib.request.urlopen(req):
              pass

          def handler(event, context):
            try:
              req_type = event.get("RequestType")
              if req_type == "Delete":
                send_response(event, context, "SUCCESS", {})
                return
              if req_type in ("Create", "Update"):
                props = event.get("ResourceProperties", {})
                res = identity.describe_user_pool_client(
                  ClientId=props["clientId"],
                  UserPoolId=props["userpoolId"]
                )
                secret = res.get("UserPoolClient", {}).get("ClientSecret", "")
                send_response(event, context, "SUCCESS", {"appSecret": secret})
                return
              send_response(event, context, "FAILED", {}, "Unsupported RequestType")
            except Exception as e:
              send_response(event, context, "FAILED", {}, str(e))
    DependsOn: UserPoolClientRole
